### ISSUE TITLE
International server 

### ISSUE THREAD

**Issue by denver-code** [GlobalArtInc/warface-api-wrapper#1]
Привет!
Столкнулся с небольшой проблемкой, есть русский сервер, с ним нет проблем, всё работает.
Но мне мимо ру нужен евро, в коде у тебя увидел линк на апи - http://api.wf.my.com/
при этом оно делает редирект на pvp.gg, где отдает еррор..
Возможно знаешь как получить апишку евро варфейса?
Пока в принципе хватает https://api.wfstats.cf/ но хотется прямо к серверам вф конечится

**Comment by GlobalKhabr** [comment]
Доброго времени суток.
API международного варфейса - api.wf.my.com. С моей стороны проблем с этим нету, я предполагаю, может быть IP-адреса с Украины перенаправляет на pvp.gg.
![Screenshot_3](https://user-images.githubusercontent.com/28756181/152305148-09ede2a9-2ca5-4735-9bbe-e340d764858c.png)

**Comment by denver-code** [comment]
Хм, возможно такое, как-то не думал об этом, надо узнать подробнее.
Спасибо!
